project:
  type: book
  output-dir: docs

book:
  title: "Wrangling genomics"
  #author: "Jane Doe"
  date: "11/16/2023"
  chapters:
    - index.qmd
    - intro.qmd
    - quality-control.qmd
    - trimming.qmd
    - variant-calling.qmd
    - automation.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
    other-links:
      - text: Introduction to Genomics Chatbot
        href: https://tsl-bioinformatics.shinyapps.io/genomics_chatbot/
        target: _blank
  pdf:
    documentclass: scrreprt

editor: visual

