# Preface {.unnumbered}

A lot of genomics analysis is done using command-line tools for three reasons:

1.  you will often be working with a large number of files, and working through the command-line rather than through a graphical user interface (GUI) allows you to automate repetitive tasks,

2.  you will often need more compute power than is available on your personal computer, and connecting to and interacting with remote computers requires a command-line interface, and

3.  you will often need to customize your analyses, and command-line tools often enable more customization than the corresponding GUI tools (if in fact a GUI tool even exists).

In a previous lesson, you learned how to use the bash shell to interact with your computer through a command line interface. In this lesson, you will be applying this new knowledge to carry out a common genomics workflow - identifying variants among sequencing samples taken from multiple individuals within a population. We will be starting with a set of sequenced reads (`.fastq` files), performing some quality control steps, aligning those reads to a reference genome, and ending by identifying and visualizing variations among these samples.

As you progress through this lesson, keep in mind that, even if you aren't going to be doing this same workflow in your research, you will be learning some very important lessons about using command-line bioinformatic tools. What you learn here will enable you to use a variety of bioinformatic tools with confidence and greatly enhance your research efficiency and productivity.

::: {.callout-important icon="false"}
## Prerequisites

This lesson assumes a working understanding of the bash shell. If you haven't already completed the Shell Genomics lesson, and aren't familiar with the bash shell, please review those materials before starting this lesson.

This lesson also assumes some familiarity with biological concepts, including the structure of DNA, nucleotide abbreviations, and the concept of genomic variation within a population.
:::

## **Schedule**

+-------+-------------------------------------------+-----------------------------------------------------------------------------+
|       | Setup                                     | Download files required for the lesson                                      |
+=======+===========================================+=============================================================================+
| 00:00 | 1\. Background and metadata               | What data are we using?\                                                    |
|       |                                           | Why is this experiment important?                                           |
+-------+-------------------------------------------+-----------------------------------------------------------------------------+
| 00:15 | 2\. Assessing read quality                | How can I describe the quality of my data?                                  |
+-------+-------------------------------------------+-----------------------------------------------------------------------------+
| 01:05 | 3\. Trimming and filtering                | How can I get rid of sequence data that does not meet my quality standards? |
+-------+-------------------------------------------+-----------------------------------------------------------------------------+
| 02:00 | 4\. Variant calling workflow              | How do I find sequence variants between my sample and a reference genome?   |
+-------+-------------------------------------------+-----------------------------------------------------------------------------+
| 03:00 | 5\. Automating a variant calling workflow | How can I make my workflow more efficient and less error-prone?             |
+-------+-------------------------------------------+-----------------------------------------------------------------------------+
| 03:45 | Finish                                    |                                                                             |
+-------+-------------------------------------------+-----------------------------------------------------------------------------+

The actual schedule may vary slightly depending on the topics and exercises chosen by the instructor.
